# Generated by Django 4.2.26 on 2025-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
