# Generated by Django 4.2.26 on 2025-11-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(default="available", max_length=20),
        ),
    ]
