# Generated by Django 4.2.26 on 2025-11-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0002_property_bathrooms_property_bedrooms_property_city_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
