# Generated by Django 4.2.26 on 2025-11-24 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
