# Generated by Django 4.2.26 on 2025-11-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_propertyimage_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="cluster",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="erf_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="estate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="flatlet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="floor_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="on_auction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="on_show",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="parking",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("townhouse", "Townhouse"),
                    ("vacant_land", "Vacant Land"),
                    ("farm", "Farm"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="repossessed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="retirement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="properties", to="properties.propertyfeature"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="properties.listingtype",
            ),
        ),
    ]
