# Generated by Django 4.2.26 on 2025-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_listingtype_propertyfeature_property_cluster_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="category",
        ),
        migrations.RemoveField(
            model_name="property",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="property",
            name="estate",
        ),
        migrations.RemoveField(
            model_name="property",
            name="on_auction",
        ),
        migrations.RemoveField(
            model_name="property",
            name="on_show",
        ),
        migrations.RemoveField(
            model_name="property",
            name="repossessed",
        ),
        migrations.RemoveField(
            model_name="property",
            name="retirement",
        ),
        migrations.RemoveField(
            model_name="property",
            name="size",
        ),
        migrations.RemoveField(
            model_name="property",
            name="status",
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
