# Generated by Django 4.2.26 on 2025-11-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0006_remove_property_category_remove_property_cluster_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="price",
        ),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="properties.propertycategory",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="cluster",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="estate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="on_auction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="on_show",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="rent_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="repossessed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="retirement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(default="available", max_length=20),
        ),
    ]
