# Generated by Django 4.2.26 on 2025-11-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_remove_property_price_property_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="category",
        ),
    ]
