# Generated by Django 4.2.26 on 2025-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_remove_property_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="PropertyCategory",
        ),
    ]
