# Generated by Django 4.2.26 on 2025-11-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_propertytype_delete_propertycategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
