# Generated by Django 4.2.26 on 2025-12-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_property_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="status",
        ),
    ]
