# Generated by Django 4.2.26 on 2025-12-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_remove_property_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Short marketing description shown on listing cards",
                max_length=255,
            ),
        ),
    ]
