# Generated by Django 4.2.26 on 2025-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingtype",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
