# Generated by Django 4.2.26 on 2025-12-31 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0013_listingtype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
